// Generated by Generator.rb
// DO NOT EDIT

import Foundation
struct Config {
	private init() {}
	static let ENABLE_LOGGING: Bool = false
	static let SDK_APPID: String = "1019154125"
	static let APP_HOST: String = "https://release.struggleblog.com"
}
