#!/bin/sh

#  ConfigGenerator.sh
#  XCConfigSample
#
#  Created by 刘波 on 2020/7/31.
#  Copyright © 2020 struggleblog. All rights reserved.

printf "//generated by ConfigGenerator.sh\n"
printf "// DO NOT EDIT\n"
printf "\nimport Foundation\n\n"

echo "enum Config { "

# 获取以 CONFIG_ 开头的变量
env | grep "CONFIG_" | \

# CONFIG_ENABLE_LOGGING_Bool=false
# CONFIG_APP_HOST_String=https:/$()/release.struggleblog.com

# =>    static let ENABLE_LOGGING_Bool=false
# =>    static let APP_HOST_String=https:/$()/release.struggleblog.com
sed "s/CONFIG_/    static let /" |\

# =>    static let ENABLE_LOGGING_: Bool=false
# =>    static let APP_HOST_: String=https:/$()/release.struggleblog.com
sed -E "s/([^_]+)$/: \1/" |\

# =>    static let ENABLE_LOGGING: Bool=false
# =>    static let APP_HOST: String=https:/$()/release.struggleblog.com
sed "s/_:/:/" |\

#=>     static let ENABLE_LOGGING: Bool=false
#=>     static let APP_HOST: String="https:/$()/release.struggleblog.com"
sed -E 's/String=(.*)/String="\1"/' |\

#=>     static let ENABLE_LOGGING: Bool = false
#=>     static let APP_HOST: String = "https:/$()/release.struggleblog.com"
sed 's/=/ = /'

echo "}"
