#!/bin/sh

#  Config.sh
#  XCConfigSample
#
#  Created by 刘波 on 2020/11/25.
#  Copyright © 2020 struggleblog. All rights reserved.

printf "//\n//\n//generated by Config.sh\n"
printf "// DO NOT EDIT\n"
printf "\nimport Foundation\n\n"

echo "struct Config { "
echo "\tprivate init() {}"

env | grep "STRUGGLE_" | \

## raw value:
## CONFIG_iOS_EVAL_KEY_String=ACTYSXZCUQ
## CONFIG_ZHUGE_REALTIME_DEBUG_Bool=false


# => iOS_EVAL_KEY_String=ACTYSXZCUQ
# => ZHUGE_REALTIME_DEBUG_Bool=false
sed "s/STRUGGLE_/    static let /" |\

# => iOS_EVAL_KEY_: String=ACTYSXZCUQ
# => ZHUGE_REALTIME_DEBUG_: Bool=false
sed -E "s/([^_]+=)/: \1/" |\

# => iOS_EVAL_KEY: String=ACTYSXZCUQ
# => ZHUGE_REALTIME_DEBUG: Bool=false
sed "s/_:/:/" |\

# => iOS_EVAL_KEY: String="ACTYSXZCUQ"
# => ZHUGE_REALTIME_DEBUG: Bool=false
sed -E 's/String=(.*)/String="\1"/' |\

# => iOS_EVAL_KEY: String = "ACTYSXZCUQ"
# => ZHUGE_REALTIME_DEBUG: Bool = false
sed 's/=/ = /'

echo "}"
