//
//
//generated by Config.sh
// DO NOT EDIT

import Foundation

struct Config { 
	private init() {}
    static let ENABLE_LOGGING: Bool = true
    static let SDK_APPID: String = "2732648263"
    static let APP_HOST: String = "https://debug.struggleblog.com"
}
