//generated by ConfigGenerator.sh
// DO NOT EDIT

import Foundation

enum Config { 
    static let APP_HOST: String = "https://release.struggleblog.com"
    static let SDK_APPID: Int = 1019154125
    static let ENABLE_LOGGING: Bool = false
}
