#!/usr/bin/ruby

#  Config.rb
#  XCConfigSample
#
#  Created by 刘波 on 2020/11/25.
#  Copyright © 2020 struggleblog. All rights reserved.


file_path = ENV["SRCROOT"] + "/" + ENV["PRODUCT_NAME"] + "/Config.swift"

file = File.new(file_path, "w+")

file.puts "// Generated by Generator.rb"
file.puts "// DO NOT EDIT"

file.puts "\nimport Foundation\n"
file.puts "struct Config {"
file.puts "\tprivate init() {}"


ENV
.keep_if { |k, _| k.start_with? "STRUGGLE_" }
.each { |k, v|
    words = k.split("_")
    words.shift
    type = words.pop
    key = words.join("_").concat(": #{type}")
    
    case k.end_with? "String"
    when true
        file.puts "\tstatic let #{key} = \"#{v}\""
    when false
        file.puts "\tstatic let #{key} = #{v}"
    end
}
file.puts "}"
file.close

